[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
